version: 2

jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - run: apt-get update
      - run: apt-get install -y build-essential npm nodejs
      - checkout
      - run: npm install
      - run: npm run build # needed because the policy and about plugin components are added during the build step
      - save_cache:
          key: v1-code-gov-front-end-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ~/circleci-code-gov-workflows
  run-lint:
    docker:
      - image: circleci/node:8.12
    steps:
      - restore_cache:
          key: v1-code-gov-front-end-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run lint
  run-jest:
    docker:
      - image: ubuntu
    steps:
      - restore_cache:
          key: v1-code-gov-front-end-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run test:ci
  run-pa11y:
    docker:
      - image: circleci/ruby:2.5.5-node-browsers
    steps:
      - restore_cache:
          key: v1-code-gov-front-end-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run serve & sleep 5; npm run test-pa11y # run server in background, then run accessibility testing

  deploy-bundle-analysis:
    docker:
      - image: ubuntu
    steps:
      - run: apt-get update
      - run: apt-get install -y build-essential git npm nodejs
      - checkout
      - run: npm install
      - run: npm run analyze
      - run: cd dist && mkdir report && cp report.html report/report.html
      - run: 'git config --global user.email "code@gsa.gov" && git config --global user.name "code.gov ci"'
      - run: CODE_GOV_RELATIVE_DIR='/dist/report' CODE_GOV_BRANCH='federalist-bundle-analysis' npm run deploy
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - run-lint:
          requires:
            - build
      - run-jest:
          requires:
            - build
      - run-pa11y:
          requires: 
            - build
      - deploy-bundle-analysis:
          filters:
            branches:
              only: master
