version: 2

references:
  container: &container
    docker:
      - image: circleci/node:10.15.1-browsers
        environment:
          CHROME_PATH: /usr/bin/google-chrome

  restore_deps: &restore_deps
    restore_cache:
      keys:
        - test-codegov-dependencies-{{ checksum "package-lock.json" }}

jobs:
  build:
    <<: *container
    steps:
      - checkout
      - restore_cache:
          keys: 
            - test-codegov-dependencies-{{ checksum "package-lock.json" }}
            - test-codegov-dependencies-

      - run: npm install
      - run: npm run build # needed because the policy and about plugin components are added during the build step
      - save_cache:
          paths:
            - ./node_modules
          key: test-codegov-dependencies-{{ checksum "package-lock.json" }}
  run-lint:
    <<: *container
    steps:
      - checkout
      - restore_cache:
          keys: 
            - test-codegov-dependencies-{{ checksum "package-lock.json" }}
            - test-codegov-dependencies-
      - run: npm install
      - run: npm run lint
  run-jest:
    <<: *container
    steps:
      - checkout
      - restore_cache:
          keys: 
            - test-codegov-dependencies-{{ checksum "package-lock.json" }}
            - test-codegov-dependencies-
      - run: npm install
      - run: npm run test:ci
  run-pa11y:
    <<: *container
    steps:
      - checkout
      - restore_cache:
          keys: 
            - test-codegov-dependencies-{{ checksum "package-lock.json" }}
            - test-codegov-dependencies-
      - run: npm install
      - run: npm run serve & sleep 5; npm run test-pa11y # run server in background, then run accessibility testing

  deploy-bundle-analysis:
    docker:
      - image: ubuntu
    steps:
      - run: apt-get update
      - run: apt-get install -y build-essential git npm nodejs
      - checkout
      - run: npm install
      - run: npm run analyze
      - run: cd dist && mkdir report && cp report.html report/report.html
      - run: 'git config --global user.email "code@gsa.gov" && git config --global user.name "code.gov ci"'
      - run: CODE_GOV_RELATIVE_DIR='/dist/report' CODE_GOV_BRANCH='federalist-bundle-analysis' npm run deploy
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - run-lint:
          requires:
            - build
      - run-jest:
          requires:
            - build
      - run-pa11y:
          requires: 
            - build
      - deploy-bundle-analysis:
          filters:
            branches:
              only: master
